theme: jekyll-theme-cayman
title: HBC's Introduction to R and differential gene expression analysis with DESeq2
description: Materials for a 3-day, hands-on Introduction to R and differential gene expression (DGE) analysis workshop.
